//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class business
    {
        public business()
        {
            this.business_position = new HashSet<business_position>();
        }
    
        public int id_business { get; set; }
        public string business_name { get; set; }
        public string adress { get; set; }
    
        public virtual ICollection<business_position> business_position { get; set; }
    }
}
