//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class education_systemEntities1 : DbContext
    {
        public education_systemEntities1()
            : base("name=education_systemEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<business> business { get; set; }
        public DbSet<business_position> business_position { get; set; }
        public DbSet<person> person { get; set; }
        public DbSet<person_business_position> person_business_position { get; set; }
        public DbSet<position> position { get; set; }
        public DbSet<quota> quota { get; set; }
        public DbSet<scores> scores { get; set; }
        public DbSet<subject> subject { get; set; }
    }
}
