//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class person_business_position
    {
        public int id_person_business_position { get; set; }
        public Nullable<int> person_id { get; set; }
        public Nullable<int> business_position_id { get; set; }
        public string username { get; set; }
        public string pwd { get; set; }
        public string estado { get; set; }
    
        public virtual business_position business_position { get; set; }
        public virtual person person { get; set; }
    }
}
