//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class person
    {
        public person()
        {
            this.quota = new HashSet<quota>();
            this.quota1 = new HashSet<quota>();
            this.person_business_position = new HashSet<person_business_position>();
        }

        [Display(Name = "ID")]
        public int id_person { get; set; }
        [Display(Name = "Nombre")]
        [StringLength(10, ErrorMessage = "Maximo de caracteres 10")]
        public string first_name { get; set; }
        [Display(Name = "Segundo Nombre")]
        [StringLength(10, ErrorMessage = "Maximo de caracteres 10")]
        public string middle_name { get; set; }
        [Display(Name = "Apellido Paterno")]
        [StringLength(10, ErrorMessage = "Maximo de caracteres 10")]
        public string last_name { get; set; }
        [Display(Name = "Apellido Materno")]
        [StringLength(10, ErrorMessage = "Maximo de caracteres 10")]
        public string second_last_name { get; set; }
        [Display(Name = "Fecha de nacimiento")]
        [DataType(DataType.DateTime), Required]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime fecha_nacimiento { get; set; }
        [Display(Name = "Cedula")]
        [StringLength(10, ErrorMessage = "Maximo de caracteres 10")]
        [RegularExpression("([0-9]*)", ErrorMessage = "La cedula debe ser solo numeros")]
        public string cedula { get; set; }
    
        public virtual ICollection<quota> quota { get; set; }
        public virtual ICollection<quota> quota1 { get; set; }
        public virtual ICollection<person_business_position> person_business_position { get; set; }
    }
}
