//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class quota
    {
        public quota()
        {
            this.scores = new HashSet<scores>();
        }
    
        public int id_quota { get; set; }
        public Nullable<int> subject_id { get; set; }
        public Nullable<int> alumno_id { get; set; }
        public Nullable<int> profesor_id { get; set; }
        public string periodo { get; set; }
    
        public virtual person person { get; set; }
        public virtual person person1 { get; set; }
        public virtual subject subject { get; set; }
        public virtual ICollection<scores> scores { get; set; }
    }
}
