//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class subject
    {
        public subject()
        {
            this.quota = new HashSet<quota>();
        }
    
        [Display(Name="ID")]
        public int id_subject { get; set; }
        [Display(Name="Codigo de materia")]
        [StringLength(10, ErrorMessage = "Maximo de caracteres 10")]
        public string codigo_subject { get; set; }

        [Display(Name = "Nombre de materia")]
        [StringLength(10, ErrorMessage = "Maximo de caracteres 10")]
        public string nombre_subject { get; set; }

        [Display(Name = "Maximo Cupo")]
        public int max_alumnos { get; set; }
        
        [Display(Name = "Descipcion de materia")]
        [StringLength(100, ErrorMessage = "Maximo de caracteres 10")]
        public string descripcion { get; set; }
        
        [Display(Name = "Hora de entrada de la materia")]
        public Nullable<System.TimeSpan> hora_entrada { get; set; }
        
        [Display(Name = "Hora de salida de la materia")]
        public Nullable<System.TimeSpan> hora_salida { get; set; }
    
        public virtual ICollection<quota> quota { get; set; }
        public List<person> profesores { get; set; }
    }
}
